### ISSUE TITLE
Libraries should be updated to work with recent graphics cards.

### ISSUE THREAD

**Issue by Ahmetf1** [autonomousvision/transfuser#114]
After spending hours trying to run local_evaluation.sh. I figured out that my graphics card RTX 3060 is not compatible with cuda 10.2. Tried different library combinations and find a working one at the end. I want to share the solution just in case somebody needs it.

- in environment.yml change `cudatoolkit=10.2` with `cudatoolkit=11.3`
- in team_code_transfuser/requirements.txt delete
```
torch==1.11.0
torchaudio==0.11.0
torchvision==0.12.0
```
- delete the existing conda environment and create a new one with the new files.
- install the remaining libraries with
```
conda activate tfuse
pip3 install torch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.0+cu113.html
pip install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.0/index.html
```

**Comment by Kait0** [comment]
Cuda compatibility is a nightmare unfortunately. 
I have systems with 2080ti where the cuda 11 libraries don't work, so we are likely keeping the repo as is.

Thanks for sharing your configuration.
I haven't tested torch 1.12, but it should work fine.
For people who want to stick with torch 1.11:
Instead of deleting torch from the requirements.txt one can also replace it with:

> --extra-index-url https://download.pytorch.org/whl/cu113
> torch==1.11.0+cu113
> --extra-index-url https://download.pytorch.org/whl/cu113
> torchaudio==0.11.0
> --extra-index-url https://download.pytorch.org/whl/cu113
> torchvision==0.12.0+cu113

and then install torch-scatter and mmcv with

> pip install torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu113.html

> pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
