### ISSUE TITLE
The submission is always in pending

### ISSUE THREAD

**Issue by jdmdj1999** [autonomousvision/transfuser#118]
Hello, I submitted the result to the leaderboard, but it was always in pending state. Have you ever encountered this problem?

**Comment by kashyap7x** [comment]
Hello! The CARLA leaderboard has limited AWS resources and receive a huge increase in the number of submissions at this time of the year, due to the CARLA challenge deadline (07/11/2022). We have also had submissions that were pending for over a week for last year's CARLA challenge. In the past, the CARLA team has often come up with a solution (such as temporarily increasing the resources or extending the challenge deadline).

The CARLA simulator has a discord server at https://discord.gg/8kqACuC. You can get the latest information in the "CARLA AD leaderboard" channel here.

The leaderboard availability should improve after the deadline.

**Comment by jdmdj1999** [comment]
Thanks a lot!
