### ISSUE TITLE
The speed of ego car in eva

### ISSUE THREAD

**Issue by HelloWorld416** [autonomousvision/transfuser#120]
Hi, I hope it does not bother you. It seems that the ego car driving slowly during the evaluation phase. May I ask you how to change the driving speed of the ego car during evaluation time?

**Comment by kashyap7x** [comment]
Hello!

The autopilot used for data generation has two parameters, `target_speed_slow` and `target_speed_fast`, which you can increase to make it drive at a higher speed.
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_autopilot/autopilot.py#L51

To increase the driving speed of the trained TransFuser model, you will either need to **re-train it with a new dataset** collected with a faster expert (recommended); or manually **increase the desired speed input to its PID controller** (not recommended, since the model was not trained to handle high speeds, and will probably have a harder time steering/avoiding collisions).
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L660

**Comment by HelloWorld416** [comment]
Thanks for your comprehensive answer, I already understand how to deal with the problem.

**Comment by Kait0** [comment]
You need to be careful when increasing the speed.
For once it will implicitly change the steering:
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L671
which is computed based on the angle to the average between the first and second predicted waypoint.
If you are driving faster, these waypoints will be farther away and hence the model will steer stronger in turns.

The second problem with driving faster is scenario 3. It becomes very hard to avoid the pedestrian running in front of the car when driving at higher speeds.
You will need to come up with a solution, that allows the autopilot to still solve the scenario 3 if you want to increase the speed a lot.

Both problems are solvable, but you need to take some care to address them. If you just naively increase the speed your DS might go down.
