### ISSUE TITLE
Porting Transfuser to BeamNG.tech

### ISSUE THREAD

**Issue by alessiogambi** [autonomousvision/transfuser#129]
Dear All, 

I do research on testing ADAS/AV and scenario synthesis [1]  using BeamNG.tech [2] and would love to run (test) your driving agent into that simulator. I know CARLA is kind of a de facto standard, but IMHO BeamNG.tech is superior when it comes to physic simulation, content, and flexibility. Further, BeamNG.tech is free for research, offers a python API, just like CARLA, and implements a wide range of sensors.

So I wonder how technically difficult would be to port Transfuser to that BeamNG.tech and whether anyone of you could support me (and my colleagues) in doing so. You can PM if you like (contact details are on my home page [3]).

Thanks!

-- Alessio

[1] List of publications: https://dblp.org/pid/50/5924.html
[2] BeamNG.tech Home page: https://beamng.tech/
[3] Dr. Alessio Gambi Home page: https://www.fh-krems.ac.at/en/university/team/alessio-gambi/

**Comment by Kait0** [comment]
Hello Mr. Alessio,

I am sure that as a commercial simulator, BeamNG has some advantages over CARLA (otherwise nobody would buy it).

> "Academic and non-commercial licenses are provided free of charge at our discretion. "

Since the simulator is only available for researchers on request and at the discretion of the company, it is not interesting for us. With such a setup, the company can change their policy at any time and deny individuals access. 
CARLA being freely accessible to everyone in our community forever is one key reason why we work work it.

> whether anyone of you could support me (and my colleagues) in doing so

We can answer questions about the codebase, but we can not help you port it to BeamNG.

> I wonder how technically difficult would be to port Transfuser to that BeamNG.tech

I can see a number of challenges in porting this code to another simulator.

1.  You will need some data to train with. Here we use an automatic labeling algorithm (expert driver). I think it is possible to transfer the ideas to other simulators, but the implementation itself depends on reading out information from CARLA and hence won't work with other simulators out of the box.
2. You will need training routes, wheaters and towns to collect data on. We use some algorithms to make sure intersections and scenarios are well represented in the dataset, that will likely not work in BeamNG. You will need to come up with solutions on your own there to make sure you have a well balanced dataset.
3. We use a kinematic bicycle model in a few places in the code. Its parameters were automatically optimized to fit the standard car using a technique from the [World on Rails](https://github.com/dotchen/WorldOnRails) paper. You will need to recompute this.
4. I would expect that all the coordinate systems will be different in BeamNG, and hence all coordinate system changes will break and have to be redone. From experience, this is quite a painful process that can take a lot of time.
5. The controllers need to be adapted to the physics of BeamNG
6. It might be tricky to get the auxiliary labels in BeamNG. Though transfuser can be trained without them, albeit at a slightly lower performance.
7. TransFuser expects goal locations in order to know where it should drive. In CARLA, these are computed by running an A* on a MAP and then sparsify the path. You will need to implement a similar mechanism.
8. The machine learning model and training will probably work without changes since it is not CARLA dependent.
9. There will likely be some things that are different in BeamNG that I don't know about, so expect some additional problems to come up.

Best Regards,
Bernhard Jaeger
