### ISSUE TITLE
What's the wp loss on town2 and town5

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/transfuser#130]
Thanks for your great job. Recently, I try to make some changes based on the transfuser dataset.  It's too much time to evaluate the performance on carla every time. Hence, I'd like to what's your wp loss  when evaluate on town2 and town5?

**Comment by Kait0** [comment]
I would be very careful with waypoint valdation loss.
It is a bad predictor of driving score. (I usually don't even check it because it is quite pointless).

I agree that evaluating on CARLA can be slow if done sequentially.
What we do to speed up evaluation is we evaluate every route in parallel using some scripts specific to our cluster and then aggregate the results using the [results parser](https://github.com/autonomousvision/transfuser/blob/2022/tools/result_parser.py).

In case you have limited ressources I can recommend the [LAV routes](https://github.com/dotchen/LAV) for evaluation. They are fewer routes in total then longest 6 and the traffic density is lower, which speeds up the simulator.

**Comment by raozhongyu** [comment]
Thanks&nbsp; a lot, I get it!

---Original---
From: "Bernhard ***@***.***&gt;
Date: Thu, Dec 1, 2022 11:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [autonomousvision/transfuser] What's the wp loss on town2 andtown5 (Issue #130)




 
I would be very careful with waypoint valdation loss.
 It is a bad predictor of driving score. (I usually don't even check it because it is quite pointless).
 
I agree that evaluating on CARLA can be slow if done sequentially.
 What we do to speed up evaluation is we evaluate every route in parallel using some scripts specific to our cluster and then aggregate the results using the results parser.
 
In case you have limited ressources I can recommend the LAV routes for evaluation. They are fewer routes in total then longest 6 and the traffic density is lower, which speeds up the simulator.

**Comment by raozhongyu** [comment]
I'd like to konw can I get the Extrinsic of the camera from your meansurements?  Is it the same with the ego_matrix?

**Comment by Kait0** [comment]
We use three different cameras.
Their configuration can be found [here](https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/config.py#L20).
At inference we only use the middle 60° FOV of each camera and then concatenate them together to form one image.

**Comment by raozhongyu** [comment]
Thanks a lot.
