### ISSUE TITLE
Problems about extending transfuser with multi-timestep input

### ISSUE THREAD

**Issue by JianLiMech** [autonomousvision/transfuser#153]
Hello dear author of transfuser, thanks a lot for your great work! I have been studying transfuser in the last weeks.

I have been studying transfuser in the last weeks. And I would like to do a extension based on transfuser with multi-time step input. If necessary, expand the code base to do so.

I read your code on github and saw that you have implemented the multi-step input module. E.g. You have the parameters such as `seq_len` and `image_seq_len` in Config.py. But I also saw some assertions to forbid a value other than 1 time-step. E.g. You wrote `assert (config.img_seq_len == 1)` in line 21 of data.py. Based on that, I assume that part of the code base is already capable of handling multi-time step input. But it is not completed, is that right? Or maybe you have already done some experiments with multi-time step input?  :)

As a starting point for me, it would be really helpful for me if you give me an impression of what has to be adapted in order to execute trainings with multi-time step input. I know that you can’t give me all the specific lines but as you are the experts of the code base I would really appreciate it if you could provide me some hints on the modules/areas which have to be specifically adapted for multi-time step input.

**Comment by Kait0** [comment]
I think this is a leftover from the CVPR codebase, the current code doesn't really support multiple input frames.
I think we ran same preliminary experiments in the past but saw no improvement.
You will need to get around causal confusion and make the temporal data useful for approximating the expert if you want to get this to work.

The current dataset is collected at 2 FPS, so with that dataset you can only have temporal inputs at that framerate.
Otherwise you will need to recollect the dataset at a denser framerate.
At inference time you need to buffer your temporal frames so that they get input to the network at the same rate as in your dataset.
You will need to adapt the dataloader to load multiple frames and change the architecture such that it can process temporal data.
