### ISSUE TITLE
 Image Resolution Issues for Data Acquisition and Testing

### ISSUE THREAD

**Issue by carryman97** [autonomousvision/transfuser#171]
Hi, I've been following your excellent work, but I have a problem. I found that when your data is collected, the resolution of the single image (left, middle, right) collected is (320, 160, 60), while the single image collected during the test (left, middle, right) is (960 , 480, 120), I would like to ask whether this has an impact on the test results?Thank you very much。

**Comment by Kait0** [comment]
This is an engineering trick to get around CARLAs bugged lens model.
We collect data at training time without image distortions at low resolution and FOV.
During test time we use a larger camera (with image distortions) and only use the the center part that correspons to the original resolution (and FOV) used in the dataset. Since image distortions are not strong in the center of the carma you end up with a mostly undistorted image.
