### ISSUE TITLE
Can you share the code about Attention Map Visualizations

### ISSUE THREAD

**Issue by suunnshine** [autonomousvision/transfuser#18]

**Comment by ap229997** [comment]
Thanks for pointing this out. I have added the attention map [visualization code](https://github.com/autonomousvision/transfuser/blob/main/transfuser/viz.py).

We visualize the attention maps from the last attention layer for each of the four heads on a subset of Town05_tiny data since it contains lots of intersections. The main change in the model (`model_viz.py`) is to return the attention maps along with the waypoint predictions.

Let me know if there are any issues with running the code.
