### ISSUE TITLE
Failed Routes in Data Generation

### ISSUE THREAD

**Issue by st3lzer** [autonomousvision/transfuser#187]
Hello!

I have a question regarding the training data generation:
It is normal that a small number of routes in the generation will fail. How did you deal with these routes? Did you rerun, delete, or just used them in training?

Thank you!

**Comment by Kait0** [comment]
Yes that is normal. I think in this project we used partial routes if all necessary files were there. Otherwise just skip or delete the route. 
We typically use [a script](https://github.com/autonomousvision/carla_garage/blob/main/generate_dataset_slurm.py) to restart crashed routes, though I don't think this is vital.

**Comment by st3lzer** [comment]
Thank you!
