### ISSUE TITLE
Transformation of bounding boxes from 3D to 2D

### ISSUE THREAD

**Issue by mANDm1412** [autonomousvision/transfuser#211]
Hi,
I have a question regarding the transformation of bounding boxes from 3D to 2D in branch 2021. When attempting to generate 2D traffic light/stop sign bounding boxes, I encountered an issue where the bounding box is incorrectly positioned. The only change I made was to the sensor size (from 400 x 300 to 900 x 256). It seems that something in `_get_2d_bb_baseline` or` _baseline_to_box` isn't functioning correctly. Here's a photo of this (see the red box): 

![0057](https://github.com/autonomousvision/transfuser/assets/136704943/976fe125-76a5-4db2-9fa6-9103c06cd3be)

I would really appreciate any help you can give to solve this.

**Comment by kashyap7x** [comment]
Hi,

I'm not sure we can help with this. I would recommend debugging by reverting the sensor size, to see if the issue is actually coming from inaccurate 3D bounding boxes in CARLA or from the transformation function. These functions in our code are leftover from initial experiments and were not debugged or used for our final model.
