### ISSUE TITLE
Latent TransFuser Ablation study with MLPs

### ISSUE THREAD

**Issue by SRajasekar333** [autonomousvision/transfuser#240]
Hello,

As described in the Supplementary Material, Section 4.2 of the paper, please provide how to train for the **Latent Transfuser Ablation with MLPs** by replacing the transformers ? 
Could you please share the pretrained model, if available ?
Thanks.

**Comment by Kait0** [comment]
This ablation is not part of the released codebase.

I added the old (not cleaned) training code and model to google docs you can download it here.
https://drive.google.com/file/d/1RV4nvM1rU9f8eI8Sv4Igl7ObpKCfqsXv/view?usp=sharing

The training option is --remove_tf_aim 1 together with  --backbone aim

Since this is not part of the released codebase we won't be able to offer support, you need to figure out how to get it to run yourself.
