### ISSUE TITLE
Dataset download is slow

### ISSUE THREAD

**Issue by GuoErXing** [autonomousvision/transfuser#249]
Hello, could you kindly upload a copy of the dataset to a Chinese domestic server or Google Drive? The download speed from Amazon S3 is very slow while using a VPN in China.

**Comment by Kait0** [comment]
The Amazon S3 storage is high speed storage. Since I don't think speed is affected by geographic distance it is more likely that your VPN provider is limiting your download speed. Perhaps you can check with them or choose a different VPN.

Hosting large datasets costs money, so we will not provide a second server unless some company is willing to sponsor it.

**Comment by GuoErXing** [comment]
OK, thanks for your reply
