### ISSUE TITLE
How to purge the GPU memory after the completion of each route scenario

### ISSUE THREAD

**Issue by MCUBE-2023** [autonomousvision/transfuser#258]
Dear author, 

I am currently running the transfuser on Town05 with 32 route_scenarios. The execution starts from route_scenari_0, but it doesn't reach route_scenario_31 as expected. Instead, the execution reaches route_scenario_6 and stops due to lack of GPU resources. I got this message on my terminal when the execution reaches  route_scenario_6: Cuda out of memory.

So here's my question: Is there a way to purge or clear the GPU memory after the completion of each route_scenario_6 before moving to the next route_scenario ? Is there a line of code that I can modify or add for this purpose?

Here's an example of what I want to do:
1- Run route_scenario_0
2- Before running route_scenario_1 --> Purge or clear the GPU memory
3- Run route_scenario_1
4- and so on.....

**Comment by Kait0** [comment]
You need to clear all major ressouces in the [destroy function](https://github.com/autonomousvision/transfuser/blob/3852e65e070f2efcfaba18fbbdb48057096b8a9e/team_code_transfuser/submission_agent.py#L601) since the leaderboard doesn't do it properly between routes.
Perhaps you also need to clear the [pytorch cache](https://pytorch.org/docs/stable/generated/torch.cuda.empty_cache.html).
