### ISSUE TITLE
About target point in training and testing

### ISSUE THREAD

**Issue by WPH-commit** [autonomousvision/transfuser#32]
Hi, I noticed that when you are collecting training data using autopilot, your target point are the far_nodes coming from _command_planner. However, when your actual model based agent is tested, it uses the _waypoint_planner to get target point which corresponds to near node. I think it is better to use the near nodes both for training and testing? Or do I miss something?

**Comment by ap229997** [comment]
near_node is the next waypoint after 4 metres whereas the far node is the next waypoint after 7 metres. During testing, I don't think it matters much whether you use near node or far node since the waypoints along the route are quite far from each other. But, I agree that it's better to keep it consistent between training and testing.
