### ISSUE TITLE
Weather control

### ISSUE THREAD

**Issue by hlaahmed** [autonomousvision/transfuser#36]
How do I change the weather ?

**Comment by ap229997** [comment]
The weather can be changed in two ways:
1. Specify the weather parameters in the routes file (see [sample_weather_route.xml](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/data/additional_routes/sample_weather_route.xml)).  This is suitable for defining evaluation routes so that they are consistent across all evaluation runs.
2. Set the weather of the world explicitly in client code (see [world.set_weather()](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/team_code/auto_pilot.py#L167)). We use this way to randomize the weathers during data generation.
