### ISSUE TITLE
UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/transfuser#4]
Thanks for your great wrok, i meet this question "UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment" can you give me some question

**Comment by raozhongyu** [comment]
I have solve this question

**Comment by yewon-lee** [comment]
Hi @raozhongyu I am facing the same issue as you've described. Did you figure out how to solve this error?

**Comment by ghost** [comment]
Hello @raozhongyu May you tell us how to solve this problem? I have met the same question with you~

**Comment by 927087638** [comment]
Hello @raozhongyu May you tell us how to solve this problem? I have met the same question with you~

**Comment by Fengtao22** [comment]
> Hello @raozhongyu May you tell us how to solve this problem? I have met the same question with you~

This reply might be late. But for others whom encounter similar issues, try to check whether the error info contains"RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error". If it is the case, then "you are trying to create the TrafficManager in a port that is busy" (https://github.com/carla-simulator/scenario_runner/issues/722). So the easy solution is to `

> pkill -9 python 

`
