### ISSUE TITLE
A data generation problem

### ISSUE THREAD

**Issue by Halcyon-Lexie** [autonomousvision/transfuser#40]
Hi, when I use the autopilot to start data generation, I get a "failure" as the following picture:
![Uploading 2021-12-23 19-24-01屏幕截图.png…]()
I know this problem is common, but I worry it will affect the final result of model training since we imitate an imperfect expert. How do you think about this?

**Comment by Halcyon-Lexie** [comment]
![Uploading 2021-12-23 19-24-01屏幕截图.png…]()

**Comment by Halcyon-Lexie** [comment]
![2021-12-23 19-24-01屏幕截图](https://user-images.githubusercontent.com/50164518/147305974-aa61f3ff-fdf3-4d1a-94ca-c83525f1b0c0.png)

**Comment by Halcyon-Lexie** [comment]
In addition, I don't why I get some black points in the images. Do you know the cause? 
![0053](https://user-images.githubusercontent.com/50164518/147306723-ff7a3c3d-05c0-43f1-8641-d6ab38e1ff24.png)

**Comment by ap229997** [comment]
Hi, sorry for the late reply.

The expert uses collision avoidance heuristics which has certain loopholes resulting in few collisions. Ideally, this should be removed from the training data but I think as long as this type of data is very less compared to the proper driving data, the model should be able to learn proper driving behavior.

These black dots are due to some [rendering issues](https://github.com/carla-simulator/carla/issues/3377) when running CARLA with opengl. You can try running with vulkan to remove these artifacts. For running with vulkan, just replace `-opengl` with `-vulkan` when launching the CARLA server.
