### ISSUE TITLE
How to see the visualizations of geometric fusion and late fusion?

### ISSUE THREAD

**Issue by fuwen666** [autonomousvision/transfuser#42]

**Comment by ap229997** [comment]
Since geometric fusion and late fusion do not use attention, they have to be visualized in a different way than transfuser. For geometric fusion, you can check the projection of different tokens in the other modality (eg. project 3D points from the LiDAR point cloud in the image space and BEV space). For late fusion, one option could be to use [GradCAM](https://arxiv.org/pdf/1610.02391.pdf).
