### ISSUE TITLE
Simple question regarding the scenarios

### ISSUE THREAD

**Issue by xinshuoweng** [autonomousvision/transfuser#59]
Hey Aditya, 

Thanks again for your work! I just have a quick question regarding the scenario files here for Town7/10:
https://github.com/autonomousvision/transfuser/blob/main/leaderboard/data/scenarios/town07_all_scenarios.json
https://github.com/autonomousvision/transfuser/blob/main/leaderboard/data/scenarios/town10_all_scenarios.json

These two files seem to be the same as the Town2 scenario file (even the key in the dictionary is still town2 not changed). Is this intentional? Is the Town2 scenario file supposed to work on town7 and 10?

Thanks!
Xinshuo

**Comment by ap229997** [comment]
The dense scenario files in this repo are sampled in a grid centered at the locations from the [reference scenarios file](https://github.com/carla-simulator/leaderboard/blob/master/data/all_towns_traffic_scenarios_public.json). Since the reference file does not contain scenarios for Town07, 10, we do not have new scenarios for these. I probably just forgot to remove these. The Town02 scenarios should technically not work on other towns since the map is different but it is possible that some spawn locations just work since the scenario density is quite high.

**Comment by xinshuoweng** [comment]
I see. Thanks for the clarification!
